### ISSUE TITLE
 api docker container not starting

### ISSUE THREAD

**Issue by youngtype** [brocoders/nestjs-boilerplate#662] opened 2022-07-26 18:00 UTC
/usr/bin/env: 'bash\r': No such file or directory
"pm ERR! Missing script: "start:prod
npm ERR! 
npm ERR! Did you mean this?
npm ERR!     npm run start:prod # run the "start:prod" package script
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-07-26T17_59_15_319Z-debug-0.log

**Comment by Shchepotin** [comment] 2022-07-27 08:00
I’m on it.

**Comment by youngtype** [comment] 2022-07-27 08:02
> I’m on it.

What do you mean?

**Comment by Shchepotin** [comment] 2022-07-27 10:27
I mean, I'm checking this issue.

**Comment by Shchepotin** [comment] 2022-07-27 10:33
@youngtype could you provide steps for reproduce? Because for me `docker-compose up -d` works fine.

**Comment by youngtype** [comment] 2022-07-27 11:02
I'm just using your "Qucik Start" instructions.
```
git clone --depth 1 https://github.com/brocoders/nestjs-boilerplate.git my-app
cd my-app/
cp env-example .env
docker-compose up -d
```
And the api container crashes with this error
![image](https://user-images.githubusercontent.com/79363260/181231728-4d8529d4-13bb-4f13-8920-aca6440b7b71.png)

**Comment by Shchepotin** [comment] 2022-07-27 15:19
@youngtype what OS are you using?

**Comment by youngtype** [comment] 2022-07-29 12:59
> @youngtype what OS are you using?

Windows 11 21H2 Docker Desktop 4.10.1 (82475)

However, on Github Actions CI same error with that script.

**Comment by Shchepotin** [comment] 2022-07-29 13:31
Got it! I let you know when this will be fixed.

**Closed** 2022-07-29 13:55 UTC

**Comment by Shchepotin** [comment] 2022-07-29 13:57
@youngtype @vladimirpetukhov fixed.

**Comment by youngtype** [comment] 2022-07-30 23:58
@Shchepotin 
Problem not resolved. All the same. 

```
/usr/bin/env: 'bash\r': No such file or directory
"pm ERR! Missing script: "start:prod
npm ERR! 
npm ERR! Did you mean this?
npm ERR!     npm run start:prod # run the "start:prod" package script
npm ERR! 
npm ERR! To see a list of scripts, run:
npm ERR!   npm run

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-07-30T23_55_42_342Z-debug-0.log
```

**Comment by youngtype** [comment] 2022-07-31 09:02
@Shchepotin This error in Docker appears only on my PC (Windows 11 Docker Desktop) because the CI e2e GitHub action passed successfully.

**Comment by youngtype** [comment] 2022-07-31 11:03
@Shchepotin In short, everything is ok, I had some kind of local problem with docker and wsl
